# Generated by Django 2.2.6 on 2019-10-03 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesserdemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_text', models.CharField(max_length=400)),
                ('line_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReadText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='line',
            name='read_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesserdemo.ReadText'),
        ),
    ]
